'''
Configuration class to set the parameters ready for API calls
Generation:
model -> Defines the LLM model to use
system_prompt -> Gives instructions to the LLM on how to behave
temperature -> Controls the randomness/variability of the answers generated by the LLM
max_completion_tokens -> Sets the maximum number of tokens that the LLM can generate
top_p -> Controls the range of tokens that the LLM can choose from based on their cumulative probability (recommended not to use together with temperature)

Response:
response_format -> Defines the expected format of the response
stream -> Determines whether the response is returned progressively as it is generated

Observability/Configuration:
metadata -> Allows additional information to be associated with the API request
'''
class Configuration:
    model = ...
    system_prompt = ...
    temperature = ...
    max_completion_tokens = ...
    top_p = ...
    response_format = ... 
    stream = ...
    metadata = ...

'''
Ex for json_schema:
response_format={
    "type": "json_schema",
    "json_schema": {
        "name": "assistant_response",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "respuesta": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                }
            },
            "required": ["respuesta", "confidence"],
            "additionalProperties": False
        }
    }
}
'''
